modLoader="javafml"
loaderVersion="[45,)"
license="All Rights Reserved"

[[mods]]
modId="death_ban"
version="1.0.0"
displayName="Death Ban"
credits="https://discord.gg/eCAHRcTYc9"
displayURL="https://discord.gg/eCAHRcTYc9"
authors="The_WereF0X"

[[dependencies.death_ban]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"




